# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lawrence Ting
tagline:          ''
description:      ''
url:              //lawrenceting.tk
baseurl:          /

author:
  name:           'Lawrence Ting'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lawrenceting/