# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Lawrence Ting
tagline:          ''
description:      'Scripts, Workflows, Learning to Code, Work in Progress etc…'
url:              http://hyde.getpoole.com

author:
  name:           'Lawrence Ting'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
