# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title/

# Setup
title:            Lawrence Ting
tagline:          'Learning to Code…'
description:      'Learning to Code…'
url:              //lawrenceting.github.io

author:
  name:           'Lawrence Ting'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/lawrenceting/lawrenceting.github.io
