# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lawrence Ting
tagline:          'Welcome'
description:      'learning to code'
url:              //lawrenceting.github.io
baseurl:          /

author:
  name:           'Lawrence Ting'
  url:            //lawrenceting.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           //github.com/lawrenceting

gems:
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
- jekyll-mentions
- jekyll-gist