# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title/

# Setup
title:            Lawrence Ting
tagline:          'Learning to Code…'
description:      'Learning to Code…'
url:              //lawrenceting.github.io

author:
  name:           'Lawrence Ting'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/lawrenceting/lawrenceting.github.io

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments :
	provider : disqus
	disqus :
		short_name : lawrenceting